name: '🌍 Terraform Automation'

on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'branch name'
        required: true

env:
  TF_VAR_subscription_id: ${{secrets.SUBSCRIPTION_ID}}
  TF_VAR_DOCKER_REGISTRY_SERVER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  TF_VAR_DOCKER_REGISTRY_SERVER_USERNAME: ${{ github.actor }}
  TF_VAR_DOCKER_REGISTRY_SERVER_URL: https://ghcr.io
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branchName }}

      - name: 🧩 HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0
      
      - name: 🔑 Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 🏗️ Terraform 
        id: init
        run: |
          DIRECTORIES=( "terraform" )
          for directory in ${DIRECTORIES[@]}; do
            cd ${directory} || exit 1
            terraform init -input=false
            terraform plan -out=tfplan -input=false
            terraform apply -input=false -auto-approve tfplan
            cd ..  
          done  
